### ISSUE TITLE
Duplication possible of the contains relationship

### ISSUE THREAD

**Issue by gregjan** [trellis-ldp/trellis-cassandra#32] opened 2018-11-29 14:58 UTC
I was running performance tests. What I found after two tests, between which I failed to reset the database, was that the root folder showed two identical ldp:contains relationships. Presumably there is only one contained resource, since the object of both triples was the same. I will look at the C* tables and report what I find there in a follow up comment.

**Comment by ajs6f** [comment] 2018-11-29 15:13
Nope, I know exactly what this is. I forgot to make t-c* check whether there is a root container before creating one, so it's going to create a new one on every startup, and those triples are that becoming visible. Fix OTW immediately!

**Comment by ajs6f** [comment] 2018-11-29 15:29
@gregjan Just added [a commit to master](https://github.com/ajs6f/trellis-cassandra/commit/e720416227ff47d81293a915840ee94c51974105)-- can you try that? Should fix this.

**Comment by ajs6f** [comment] 2018-12-01 13:54
@gregjan When you have a chance, please confirm that this issue is fixed (or not!) and close this ticket as is appropriate. Thanks!

**Comment by ajs6f** [comment] 2018-12-13 14:40
@gregjan Did you have a chance to check whether [this](https://github.com/ajs6f/trellis-cassandra/commit/e720416227ff47d81293a915840ee94c51974105) delivered a fix?

**Comment by ajs6f** [comment] 2019-01-16 14:43
@gregjan Just a ping on this ticket-- did the fix mentioned in https://github.com/trellis-ldp/trellis-cassandra/issues/32#issuecomment-442875457 do the job?

**Comment by ajs6f** [comment] 2019-02-21 18:11
Based on our 'phone conversation the other day, I'm going to close this. Cool, @gregjan?

**Comment by gregjan** [comment] 2019-03-06 15:02
I am seeing this issue again. I will copy my comment in here from the consistency feature, where it does exactly belong. In short, the folder test has raised this issue again.

> <http://ciber-vs1.umd.edu:10080/>
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv> .

**Comment by gregjan** [comment] 2019-03-06 15:04
So I think I have uncovered that duplication bug again, that may relate to consistency, in my testing. I am seeing multiple contains relationships to a child from the root node in the new folder test. You can see that root folder here:
http://ciber-vs1.umd.edu:10080/

There are 46 contains relationships to the same subfolder, which was created via a POST with the slug of "srv". This resulted from a test where parallel workers would have tried to create the folder and all but the first one would expect a 409 response. I also find it interesting that there are only 46, while there were 11963 unique users recorded in ES. So we don't have 11963 contains relations, only 46.. I will post a follow up with what I see in the C* table.

**Comment by gregjan** [comment] 2019-03-06 15:08
> cqlsh:trellis> select * from basiccontainment;

 container     | identifier       | created
---------------+------------------+--------------------------------------
 trellis:data/ | trellis:data/srv | 3034b1b0-3f64-11e9-a0cd-75dc2f8c34a4
 trellis:data/ | trellis:data/srv | 3033a040-3f64-11e9-a0cd-75dc2f8c34a4
 trellis:data/ | trellis:data/srv | 30337934-3f64-11e9-a0cd-75dc2f8c34a4
 trellis:data/ | trellis:data/srv | 30337933-3f64-11e9-a0cd-75dc2f8c34a4
 trellis:data/ | trellis:data/srv | 30337932-3f64-11e9-a0cd-75dc2f8c34a4
 trellis:data/ | trellis:data/srv | 30337931-3f64-11e9-a0cd-75dc2f8c34a4
 trellis:data/ | trellis:data/srv | 30337930-3f64-11e9-a0cd-75dc2f8c34a4
 trellis:data/ | trellis:data/srv | 302e4915-3f64-11e9-9acd-f1fd5771304a
 trellis:data/ | trellis:data/srv | 302e4915-3f64-11e9-838d-1b40b670cc8f
 trellis:data/ | trellis:data/srv | 302e4914-3f64-11e9-9acd-f1fd5771304a
 trellis:data/ | trellis:data/srv | 302e4914-3f64-11e9-838d-1b40b670cc8f
 trellis:data/ | trellis:data/srv | 302e4913-3f64-11e9-9acd-f1fd5771304a
 trellis:data/ | trellis:data/srv | 302e4913-3f64-11e9-838d-1b40b670cc8f
 trellis:data/ | trellis:data/srv | 302e4912-3f64-11e9-9acd-f1fd5771304a
 trellis:data/ | trellis:data/srv | 302e4912-3f64-11e9-838d-1b40b670cc8f
 trellis:data/ | trellis:data/srv | 302e4911-3f64-11e9-9acd-f1fd5771304a
 trellis:data/ | trellis:data/srv | 302e4911-3f64-11e9-838d-1b40b670cc8f
 trellis:data/ | trellis:data/srv | 302e4910-3f64-11e9-9acd-f1fd5771304a
 trellis:data/ | trellis:data/srv | 302e4910-3f64-11e9-838d-1b40b670cc8f
 trellis:data/ | trellis:data/srv | 302b3bd0-3f64-11e9-8f2d-7bb57da4be02
 trellis:data/ | trellis:data/srv | 302b14c4-3f64-11e9-8f2d-7bb57da4be02
 trellis:data/ | trellis:data/srv | 302b14c3-3f64-11e9-8f2d-7bb57da4be02
 trellis:data/ | trellis:data/srv | 302b14c2-3f64-11e9-8f2d-7bb57da4be02
 trellis:data/ | trellis:data/srv | 302b14c1-3f64-11e9-8f2d-7bb57da4be02
 trellis:data/ | trellis:data/srv | 302b14c0-3f64-11e9-8f2d-7bb57da4be02

**Comment by gregjan** [comment] 2019-03-06 15:10
> cqlsh:trellis> select * from immutabledata ;

 identifier       | created                         | quads
------------------+---------------------------------+-------
 trellis:data/srv | 2019-03-05 16:31:54.978000+0000 |  null
 trellis:data/srv | 2019-03-05 16:31:54.977000+0000 |  null
 trellis:data/srv | 2019-03-05 16:31:54.942000+0000 |  null
 trellis:data/srv | 2019-03-05 16:31:54.940000+0000 |  null
 trellis:data/srv | 2019-03-05 16:31:54.939000+0000 |  null
 trellis:data/srv | 2019-03-05 16:31:54.909000+0000 |  null
 trellis:data/srv | 2019-03-05 16:31:54.908000+0000 |  null

**Comment by gregjan** [comment] 2019-03-06 15:18
Lastly, in the mutabledata table, I see similar duplication for the trellis:data/srv objects.

25 rows like this:
> trellis:data/srv | 3034b1b0-3f64-11e9-a0cd-75dc2f8c34a4 |             null | trellis:data/ | 2019-03-05 16:31:54.000000+0000 |   null | http://www.w3.org/ns/ldp#BasicContainer |     null | 2019-03-05 16:31:54.955000+0000 | <trellis:data/srv> <http://purl.org/dc/terms/title> "srv" <http://www.trellisldp.org/ns/trellis#PreferUserManaged> .\n<trellis:data/srv> <http://purl.org/dc/terms/extent> "0" <http://www.trellisldp.org/ns/trellis#PreferUserManaged> .\n

However, I also see 4 rows representing the root node:

>     trellis:data/ | 2fead770-3f64-11e9-a0cd-75dc2f8c34a4 |             null |          null | 2019-03-05 16:31:54.000000+0000 |   null | http://www.w3.org/ns/ldp#BasicContainer |     null | 2019-03-05 16:31:55.061000+0000 |                                                                                                                                                  

The uuids are different in all cases within a table, from my spot tests.

**Comment by gregjan** [comment] 2019-03-06 15:34
Note that the trellis keyspace on my C* cluster shows a replication factor of just 1. So additional consistency may not help. There is not collision between the various items, since the created timestamp Instant is included in the primary key. In fact each may or may not be in the same partition.

Note that the root node is created at webapp startup, which is happening on four nodes in this recent test. These node partition keys include the Instant, which varies slightly for each root.

I wonder if we need the instant in the partition key at all? Without it we can hash predict the C* nodes that have our data based on path alone. I also wonder if we are going to need a "lightweight transaction", adding "IF NOT EXISTS" to the InsertImmutable and possibly other queries. I can give this a shot locally.

**Comment by acoburn** [comment] 2019-03-06 16:05
The `basiccontainment` table is a [materialized view](https://github.com/trellis-ldp/trellis-cassandra/blob/master/src/test/resources/load.cql#L22-L25) that queries the `mutabledata` table. From what I can tell, both `ResourceService::create` and `ResourceService::replace` issue `INSERT INTO ...` requests to the `mutabledata` table, so any `replace` operation (e.g. PUT or PATCH) will lead to duplicate rows in that table for a given identifier (this may be intentional for storing mementos). Presumably, the `DISTINCT` keyword could be added to that materialized view query, but I'm not sure if that would consider the case where a child resource has been deleted and should be excluded from the results altogether.

**Comment by gregjan** [comment] 2019-03-06 16:11
I'm not sure either, but I did realize that the Instant inclusion is probably due to the versioning requirements. So that makes more sense to me now. It does seem like a filter is missing here to return only the most recent contents.

**Comment by gregjan** [comment] 2019-03-06 16:35
Given the schema, it seems like the CassandraResource.basicContainmentTriples() method should include some filtering, or that the underlying view should include that. I am wondering if the duplicate rows are part of memento support or not. Perhaps some, but not all.. If the triple between parent and child already exists, then do we need the new row in order to update the timestamp?

**Comment by gregjan** [comment] 2019-03-06 19:33
Hmm, it strikes me that a POST or a PUT would simply update the object in question, creating a new mutable metadata record. The bug seems to in fact be that contains triples are being reported out redundantly for all revisions of the container, i.e. it is a GET error, rather than an error in the recorded data. (409s are for checksum mismatch or unsupported triples, not for Conflicting LDP paths, it seems.)

**Comment by gregjan** [comment] 2019-03-06 19:34
As an aside, it seems like my test scenario should check if the folder exists before POSTing a new copy of it, unless we want to test that function exhaustively.

**Comment by gregjan** [comment] 2019-03-06 20:00
Looks like the materialized view has this:
.. WITH CLUSTERING ORDER BY (identifier ASC, created DESC) ..

So this means that the results should stream out in default order that way, with a series of mementos for each child in turn. The first one of each should be the latest one.

**Comment by gregjan** [comment] 2019-03-06 20:39
I think one fix is to add .distinct() to the basicContainmentTriples() method's streaming pipeline. Adding "DISTINCT" to the query of the current view does not work, due to C* restrictions of DISTINCT to the partition key, which does not currently include "identifier" only "container". If we update the materialized view to include the identifier in the partition key:
`.. PRIMARY KEY ((container, identifier), created) ..` (added inner parens)
Then we can use DISTINCT container, identifier and throw away the extra column, getting one copy of each child relationship. (Have to ALLOW FILTERING in the query also..)

**Comment by gregjan** [comment] 2019-03-07 19:33
I have a test of this ready to go, whenever I can get back to some decent wifi for the builds.

**Comment by gregjan** [comment] 2019-03-12 14:53
I will check the triples stored for the container for the contains relationship, since I still find one extra triple in the GET output.

**Comment by gregjan** [comment] 2019-03-12 17:13
Here is the example of a container that shows duplicate relationships. This is after a distinct() was added to the basicContainmentTriples() method:

```
jansen@X1:~$ curl http://ciber-vs1.umd.edu:10080/srv/ciber/Transfer+Notes
<http://ciber-vs1.umd.edu:10080/srv/ciber/Transfer+Notes>
        <http://purl.org/dc/terms/extent>  "2" ;
        <http://purl.org/dc/terms/title>  "Transfer+Notes" ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv/ciber/Transfer+Notes/nara1_vault10> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv/ciber/Transfer+Notes/nara1_vault6> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv/ciber/Transfer+Notes/nara2_vault10> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv/ciber/Transfer+Notes/nara1_vault10> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv/ciber/Transfer+Notes/nara1_vault6> ;
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/srv/ciber/Transfer+Notes/nara2_vault10> .
```

When I look at the mutabledata table for this identifier, I see that the latest row has this quads text:

```
 <trellis:data/srv/ciber/Transfer+Notes> <http://purl.org/dc/terms/title> "Transfer+Notes" <http://www.trellisldp.org/ns/trellis#PreferUserManaged> .\n<trellis:data/srv/ciber/Transfer+Notes> <http://purl.org/dc/terms/extent> "2" <http://www.trellisldp.org/ns/trellis#PreferUserManaged> .\n
```
There are various timestamped records that are identical to this one and I do *not* see any contains relationships in the stored quads. Note that there are no quads stored for this identified in the immutabledata table.

**Comment by gregjan** [comment] 2019-03-21 17:06
Okay, I can confirm that after adding distinct() in CassandraResource.basicContainmentTriples() results in exactly 2 copies of each containment triple in output. It looks to me as if the logic of PreferContainment and PreferMembership in the calling code (CassandraResource#125) is not mutually exclusive.

**Comment by ajs6f** [comment] 2019-03-21 17:30
Awesome, @gregjan, that's a really precise diagnostic. I'll get on a fix right away.

**Comment by ajs6f** [comment] 2019-03-21 17:50
Hang on, before I do: @acoburn, take a look at @gregjan's comment above. If he's right, then is it a question of the backend emitting distinct quads and the HTTP layer creating triples by dropping the graph slot? That's not wrong, from the semantic POV (and the responses at HTTP that @gregjan is seeing aren't wrong, in that sense) but it does seem to be surprising. Do we need to add `::distinct` up there, or should we make a claim about expectations? I tend to the former position.

**Comment by ajs6f** [comment] 2019-03-21 17:58
Or again, @gregjan, am I misunderstanding the problem: are the other Trellis backends you've seen showing this problem?

**Comment by gregjan** [comment] 2019-03-21 18:47
Good question, I will start one and see.

**Comment by gregjan** [comment] 2019-03-21 19:12
I just managed *not* to duplicate this on trellis external db (version 2.1-SNAPSHOT). Added three resources at the root. They were only reported once as "contains" objects. Then I verified the non-dupe at one level below root, inside a container.

**Comment by gregjan** [comment] 2019-03-21 19:15
Just verified it on trellis-extdb:0.3.0-SNAPSHOT image too.

**Comment by ajs6f** [comment] 2019-03-21 19:20
Interesting, so it's not what I suggested above, and what's more, it's not quite what @gregjan suggested. @gregjan, can you show me an example request that you're making to get this behavior? I don't think it could be a case of the triple being added to both graphs, because there's no way I can see them being both being flattened and streamed to triples. But I'm not sure what your settings are. Are you sending any `Prefer` headers?

**Comment by ajs6f** [comment] 2019-03-21 19:24
Also, not to beat the logging horse, but [this](https://github.com/trellis-ldp/trellis-cassandra/blob/master/impl/src/main/java/edu/si/trellis/CassandraResource.java#L137) line does give us the option to turn logging up to `TRACE` and see what containment triples are being built.

**Comment by gregjan** [comment] 2019-03-21 19:24
Hmm, my recent test added containers to other containers. Perhaps I should stick to my original case, which was adding binaries to containers.. BRB

**Comment by gregjan** [comment] 2019-03-21 19:48
Here is a link to my session that duplicates it using container objects this time. Didn't set any Prefer headers in my first GET, but I did in a second request (include PreferContainment). https://gist.github.com/gregjan/115c860921d259ea151c87703e5cccfd

**Comment by gregjan** [comment] 2019-03-21 19:49
Now when I omit PreferContainment, I see only one contains relationship:
```
jansen@X1:~$ curl -H "Prefer: return=representation; omit=\"http://www.w3.org/ns/ldp#PreferContainment\"" http://ciber-vs1.umd.edu:10080/cbad3300-337f-40f9-aeaf-592425dc2c9d
<http://ciber-vs1.umd.edu:10080/cbad3300-337f-40f9-aeaf-592425dc2c9d>
        <http://www.w3.org/ns/ldp#contains>  <http://ciber-vs1.umd.edu:10080/cbad3300-337f-40f9-aeaf-592425dc2c9d/a6a6b759-c0fb-46e0-a1b2-4e13002ff0ec> .
```

**Comment by gregjan** [comment] 2019-03-21 19:50
I apologize if this is the intended functionality w/regards to spec!

**Comment by ajs6f** [comment] 2019-03-21 19:50
Aha! And just to be clear, is that the _exact same sequence_ you used for the other backends, including the last request with `PreferContainment` omitted?

**Comment by ajs6f** [comment] 2019-03-21 19:52
Right, that's what I'm trying to figure out. It's surprising no matter what, so we probably have some work to do, but I'm trying to figure out whether `t-c*` is doing something _wrong_  or whether Trellis is doing everything right ("semantically" and to the spec) but could be a little more "ergonomic" by dropping duplicate triples. Or something else.

**Comment by gregjan** [comment] 2019-03-21 19:52
Nope. In fact I never set Prefer headers in the test of the DB back end. That test only showed one contains relationship w/o Prefer header set, so I didn't see a need at that point.

**Comment by ajs6f** [comment] 2019-03-21 19:56
Ok, are you saying that [this](https://gist.github.com/gregjan/115c860921d259ea151c87703e5cccfd) sequence is a test that distinguishes `t-c*` from the other backends? Duplicate triples from `t-c*` but not from the others? I'm sorry to be so finicky about this, but it's to a good cause; I'm going to reproduce the behavior.

**Comment by gregjan** [comment] 2019-03-21 19:58
NOTE: I just ran the same test on the DB back end. If I Prefer to omit containment representations there, then I don't see *any* contains relationships reported at all.

**Comment by gregjan** [comment] 2019-03-21 20:01
It looks to me that the other back end (DB) does not consider the contains triples to be a part of the PreferMembership representation, on the PreferContainment representation.

**Comment by ajs6f** [comment] 2019-03-21 20:06
Okay, so `t-c*` is emitting one containment triple when you omit `PreferContainment` and two when you do not omit it?

**Comment by gregjan** [comment] 2019-03-21 20:07
Yes, indeed.

**Comment by ajs6f** [comment] 2019-03-21 20:10
Ok, cool. Can you possibly run that sequence (set up, request with no prefers, request with omit `PreferContainment`) at logging levels `DEBUG` for `org.trellisldp` and `TRACE` for `edu.si`? That should enable me to see where Trellis is changing its calls to the backend for those different requests. Then I can figure what the backend is doing differently, if anything.

**Comment by gregjan** [comment] 2019-03-21 20:11
Sure thing. Back in 5 mins or so.

**Comment by gregjan** [comment] 2019-03-21 20:31
I thought this had trace turned on, but I don't see any TRACE lines. Anyway, here is my first attempt with both session and logs:
https://gist.github.com/gregjan/ce621282223141e1e53ccb68843f17f7

**Comment by gregjan** [comment] 2019-03-21 20:34
Turning logging back up and running again.. 10 mins

**Comment by gregjan** [comment] 2019-03-21 20:44
Ouch, that build failed to start for some reason related to the config provider. I'll have to dig into that tomorrow. Hope that the debug session above helps somewhat in the meantime.

**Comment by ajs6f** [comment] 2019-03-21 20:49
@acoburn, are you using `Resource::stream(Collection<IRI>)` and `:: stream(IRI)` to select for different `Prefer` headers?

**Comment by ajs6f** [comment] 2019-03-21 20:51
[Looks like no.](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java#L329)

**Comment by ajs6f** [comment] 2019-03-21 20:54
@gregjan One last question for tomorrow; what do you get when you omit both `PreferContainment` and `PreferMembership`?

**Comment by ajs6f** [comment] 2019-03-21 21:05
@gregjan Never mind. I've just read the specification more carefully, and I think what's happening is much simpler than anything we've been talking about. It's simply this: I absentmindedly put triples in the `PreferMembership` graph using the `ldp:contains` predicate when I should have used the `ldp:member` predicate. I really think that may be all that's going on here, and if so, I can fix it instantly (and @acoburn and I can write some tests!).

**Comment by ajs6f** [comment] 2019-03-21 21:19
Ok, @gregjan, please try this [new commit](https://github.com/trellis-ldp/trellis-cassandra/commit/b3e6afaf8d001621821c13f41db748bb7e0274f9) before anything else. I suspect strongly that it will fix our problem and close this ticket.

**Comment by acoburn** [comment] 2019-03-22 04:22
I've been on the road all day, so I'm just catching up on this thread. The one thing I'd mention here is that, given that the T-C* implementation doesn't support Direct or Indirect containers, there should _never_ be any membership triples. Membership triples only apply to non-basic containment. And so [this line](https://github.com/trellis-ldp/trellis-cassandra/blob/master/impl/src/main/java/edu/si/trellis/CassandraResource.java#L126) really shouldn't be there. Or at least, it shouldn't be there for basic containers.

**Comment by acoburn** [comment] 2019-03-22 04:33
@ajs6f thanks for pointing out [this line](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java#L329). I'd like to look at that more closely, but I _think_ we should be calling `::stream(Collection<IRI>)` so that the irrelevant categories of triples are never fetched in the first place. That should be much more efficient than calling `::stream().filter(...)`

**Comment by ajs6f** [comment] 2019-03-22 11:35
@acoburn I'm not sure how you're figuring that (meaning where in spec we get that explicitly), but I'm happy to believe you, and annoyingly, there is only one example in the spec that shows behavior with `Prefer` and it is a direct container. I can happily just remove the membership triples, and that _should_ fix @gregjan's duplicates as well.

**Comment by ajs6f** [comment] 2019-03-22 11:36
Yes , I have no idea why we would want to fetch _all_ the tuples and then filter them. Maybe we hadn't introduced `::stream(Collection<IRI>)` or `::stream(IRI)` yet?

**Comment by acoburn** [comment] 2019-03-22 11:39
From the LDP spec, defining LDP-DC and LDP-IC:

> Linked Data Platform Direct Container (LDP-DC)
> An LDPC that adds the concept of membership, allowing the flexibility of choosing what form its membership triples take, and allows members to be any resources [WEBARCH], not only documents.

> Linked Data Platform Indirect Container (LDP-IC)
> An LDPC similar to a LDP-DC that is also capable of having members whose URIs are based on the content of its contained documents rather than the URIs assigned to those documents.

Note how an LDP-DC _adds the concept of membership_.

And then, (from non-normative language):

> Sometimes you have to build on existing models incrementally, so you have fewer degrees of freedom in the resource model. In these situations, it can be useful to help clients map LDP patterns onto existing vocabularies, or to include members not created via the container; LDP Direct Containers meet those kinds of needs. Direct Containers allow membership triples to use a subject other than the container itself as the consistent membership value, and/or to use a predicate from an application's domain model as the membership predicate.

**Comment by ajs6f** [comment] 2019-03-22 11:43
To me:
>  Direct Containers allow membership triples to use a subject other than the container itself as the consistent membership value

implied that what's being introduced is the option "to use a subject other than the container itself", not the idea of membership triples and similarly "An LDPC that adds the concept of membership, allowing the flexibility of choosing what form its membership triples take," introduced independent membership, not membership triples.

In any event, I'm happy to buy your interpretation, because it makes for less code for me! I'm testing a commit right now and hopefully @gregjan will be able to try it today.

**Comment by ajs6f** [comment] 2019-03-22 11:52
Okay, [that commit](https://github.com/trellis-ldp/trellis-cassandra/commit/b33dec5bed08d7d53f4dc2d313af57774f7da763) is in, @gregjan give it a shot!

**Comment by gregjan** [comment] 2019-03-22 14:36
Testing this latest commit next. Thanks y'all.

**Comment by ajs6f** [comment] 2019-03-22 14:39
Cool. There is one more commit after that, but it shouldn't affect this question. (It's in response to https://github.com/trellis-ldp/trellis/issues/371.)

**Comment by gregjan** [comment] 2019-03-22 15:09
Okay, I tested it, including the latest commit as well. This is resolved! When I do a plain get, it returns just one contains triple per child. When I omit ldp:PreferContainment it returns no contains triples, as expected.

**Comment by ajs6f** [comment] 2019-03-22 15:10
👏 🎈 💝

**Closed by ajs6f** 2019-03-22 15:10 UTC
Labels: bug
