### ISSUE TITLE
Thorntail trying IP6 before IP4

### ISSUE THREAD

**Issue by gregjan** [trellis-ldp/trellis-cassandra#29] opened 2018-11-26 16:23 UTC
I'm getting a startup error that is related to wildfly. It seems like it is missing a protocol dependency? Have you seen this before?

```
teststack_trellis-cassandra.1.jk24uccsie9x@ciber-vs1.umd.edu    | 2018-11-26 16:19:02,222 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
teststack_trellis-cassandra.1.jk24uccsie9x@ciber-vs1.umd.edu    |     ("subsystem" => "undertow"),
teststack_trellis-cassandra.1.jk24uccsie9x@ciber-vs1.umd.edu    |     ("server" => "default-server"),
teststack_trellis-cassandra.1.jk24uccsie9x@ciber-vs1.umd.edu    |     ("http-listener" => "default")
teststack_trellis-cassandra.1.jk24uccsie9x@ciber-vs1.umd.edu    | ]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.undertow.listener.default" => "WFLYUT0082: Could not start 'default' listener.
teststack_trellis-cassandra.1.jk24uccsie9x@ciber-vs1.umd.edu    |     Caused by: java.net.SocketException: Protocol family unavailable"}}

```

**Comment by ajs6f** [comment] 2018-11-26 16:32
Yes, @gregjan that is almost certainly it-- I thought I had managed to do some Thorntail trickery to make it so that end deployers wouldn't need to do that. Apparently not.

Glad you know the workaround (which is only relevant on some systems, but totally necessary there) and can you confirm here that that was the problem? If so, I will take a harder look at fixing it in the code.

**Comment by gregjan** [comment] 2018-11-26 17:42
This did resolve the issue, which was within a docker openjdk-8 container build. I added the flag to the startup script, i.e. within webapp/docker_command.sh. I did not need that flag in my local JRE (openjdk version "1.8.0_181").

**Comment by ajs6f** [comment] 2018-11-26 17:51
I'm going to edit the title of this ticket, cool?

**Comment by ajs6f** [comment] 2018-11-29 15:38
Yep, this is an issue for others, and [it seems to have something to do with Docker](https://issues.jboss.org/browse/THORN-94). That having been said, the only way I've found to fix it is to pass that flag (as you use above). 

The problem is that we can't do that from the app. IOW, by the time that Thorntail gets to deploying the app code, the damage is done, so to speak-- it's already trying to bind to IP6.

I'll do some more research into the container side of this (maybe other Java frameworks have this problem and have other ideas), but for now, we may need to just liberally slather on that system property to go forward.

**Comment by ajs6f** [comment] 2018-11-29 16:02
@gregjan Does [this](https://forums.docker.com/t/containers-always-resolve-names-to-ipv6-addresses/10747/2) look relevant? I wonder if it's possible to avoid using names? (Sounds unlikely, but...)

**Comment by ajs6f** [comment] 2018-12-01 14:06
I'm now confident that sadly, there is nothing we can do from inside the app itself about this-- we need to pass in the system property or otherwise configure at the Java invocation to prefer IPv4. @gregjan, I've [updated the `README`](https://github.com/ajs6f/trellis-cassandra/commit/cd47fbc20b99dea068ff5e5425152114f6248018) to document this issue-- can we close it?

**Comment by ajs6f** [comment] 2019-04-10 18:48
@gregjan, I'm going to close this, since it appears to be an issue between Java and Docker, not a `t-c*`-specific issue. Are you cool with that?

**Comment by gregjan** [comment] 2019-04-11 13:24
Yes, sounds good. We have a docker-specific configuration for it.

**Comment by ajs6f** [comment] 2019-04-11 13:59
Word.

**Closed by ajs6f** 2019-04-11 13:59 UTC
Labels: bug
